# هذا الملف يحتوي على خرائط تحويل الرموز لكل منصة

# CoinGecko ID mapping
ids_map = {
    "BTCUSDT": "bitcoin",
    "ETHUSDT": "ethereum",
    "BNBUSDT": "binancecoin",
    "SOLUSDT": "solana",
    "XRPUSDT": "ripple",
    "DOGEUSDT": "dogecoin",
    "ADAUSDT": "cardano",
    "AVAXUSDT": "avalanche-2",
    "TONUSDT": "toncoin",
    "DOTUSDT": "polkadot",
    "TRXUSDT": "tron",
    "LINKUSDT": "chainlink",
    "MATICUSDT": "matic-network",
    "SHIBUSDT": "shiba-inu",
    "BCHUSDT": "bitcoin-cash",
    "LTCUSDT": "litecoin",
    "NEARUSDT": "near",
    "ICPUSDT": "internet-computer",
    "UNIUSDT": "uniswap",
    "APTUSDT": "aptos",
    "ETCUSDT": "ethereum-classic",
    "STXUSDT": "stacks",
    "IMXUSDT": "immutable-x",
    "INJUSDT": "injective-protocol",
    "FILUSDT": "filecoin",
    "HBARUSDT": "hedera-hashgraph",
    "ARBUSDT": "arbitrum",
    "OPUSDT": "optimism",
    "RUNEUSDT": "thorchain",
    "VETUSDT": "vechain"
}

# Coinbase pair mapping
symbol_map = {
    "BTCUSDT": "BTC-USD",
    "ETHUSDT": "ETH-USD",
    "BNBUSDT": "BNB-USD",
    "SOLUSDT": "SOL-USD",
    "XRPUSDT": "XRP-USD",
    "DOGEUSDT": "DOGE-USD",
    "ADAUSDT": "ADA-USD",
    "AVAXUSDT": "AVAX-USD",
    "TONUSDT": "TON-USD",
    "DOTUSDT": "DOT-USD",
    "TRXUSDT": "TRX-USD",
    "LINKUSDT": "LINK-USD",
    "MATICUSDT": "MATIC-USD",
    "SHIBUSDT": "SHIB-USD",
    "BCHUSDT": "BCH-USD",
    "LTCUSDT": "LTC-USD",
    "NEARUSDT": "NEAR-USD",
    "ICPUSDT": "ICP-USD",
    "UNIUSDT": "UNI-USD",
    "APTUSDT": "APT-USD",
    "ETCUSDT": "ETC-USD",
    "STXUSDT": "STX-USD",
    "IMXUSDT": "IMX-USD",
    "INJUSDT": "INJ-USD",
    "FILUSDT": "FIL-USD",
    "HBARUSDT": "HBAR-USD",
    "ARBUSDT": "ARB-USD",
    "OPUSDT": "OP-USD",
    "RUNEUSDT": "RUNE-USD",
    "VETUSDT": "VET-USD"
}
